name: Build and Deploy Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Mirror to second repo
      run: |
        git remote add mirror https://github.com/myouthful/TECH-Bootcamp-Portal.git
        git push mirror main --force
      env:
        GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build web
      run: flutter build web --release
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web